from bs4 import BeautifulSoup
import nltk

import requests
import re
import json


req = requests.get('http://web.archive.org/web/20030219072854/http://timecube.com/')

if req.status_code != 200:
    raise Exception("ERROR %i" % req.status_code)


soup = BeautifulSoup(req.content, 'html.parser')
content = soup.find_all(['blockquote'])
text = '\n'.join([c.text for c in content])
data = nltk.word_tokenize(re.sub(r'[*\s]+|[\.\-]{2,}', ' ', text))
data = data[:data.index('E-MAIL')]
data.append('.')


order = 4
chain = {'$ORDER': order}
queue = []

for token in data:
    if len(queue) > order:
        queue.pop(0)

    for i in range(order):
        q = queue[i:]
        if len(q):
            key = ' '.join(q)
            if chain.get(key):
                chain[key].append(token)
            else:
                chain[key] = [token]

    queue.append(token)

f = open('./js/chain_data.js', 'w')
f.write('// generated by gen.py\nexport default %s' % json.dumps(chain))
f.close()
